/**
 * @fileoverview gRPC-Web generated client stub for authentication
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: protos/user.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.authentication.UserGrpcClient');
goog.provide('proto.authentication.UserGrpcPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.authentication.CredentialsDto');
goog.require('proto.authentication.MingleUserDto');
goog.require('proto.authentication.SuccessMsg');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authentication.UserGrpcClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authentication.UserGrpcPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authentication.CredentialsDto,
 *   !proto.authentication.MingleUserDto>}
 */
const methodDescriptor_UserGrpc_login = new grpc.web.MethodDescriptor(
  '/authentication.UserGrpc/login',
  grpc.web.MethodType.UNARY,
  proto.authentication.CredentialsDto,
  proto.authentication.MingleUserDto,
  /**
   * @param {!proto.authentication.CredentialsDto} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authentication.MingleUserDto.deserializeBinary
);


/**
 * @param {!proto.authentication.CredentialsDto} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authentication.MingleUserDto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authentication.MingleUserDto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authentication.UserGrpcClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authentication.UserGrpc/login',
      request,
      metadata || {},
      methodDescriptor_UserGrpc_login,
      callback);
};


/**
 * @param {!proto.authentication.CredentialsDto} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authentication.MingleUserDto>}
 *     Promise that resolves to the response
 */
proto.authentication.UserGrpcPromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authentication.UserGrpc/login',
      request,
      metadata || {},
      methodDescriptor_UserGrpc_login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authentication.MingleUserDto,
 *   !proto.authentication.SuccessMsg>}
 */
const methodDescriptor_UserGrpc_create = new grpc.web.MethodDescriptor(
  '/authentication.UserGrpc/create',
  grpc.web.MethodType.UNARY,
  proto.authentication.MingleUserDto,
  proto.authentication.SuccessMsg,
  /**
   * @param {!proto.authentication.MingleUserDto} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authentication.SuccessMsg.deserializeBinary
);


/**
 * @param {!proto.authentication.MingleUserDto} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authentication.SuccessMsg)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authentication.SuccessMsg>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authentication.UserGrpcClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authentication.UserGrpc/create',
      request,
      metadata || {},
      methodDescriptor_UserGrpc_create,
      callback);
};


/**
 * @param {!proto.authentication.MingleUserDto} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authentication.SuccessMsg>}
 *     Promise that resolves to the response
 */
proto.authentication.UserGrpcPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authentication.UserGrpc/create',
      request,
      metadata || {},
      methodDescriptor_UserGrpc_create);
};


}); // goog.scope

